@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Model
Class Profile
Class ProfileList
Class ProfileManager
Class Module
Class ModuleList
Class ModuleManager
Class Course
Class CourseList
Class CourseManager
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Profile {
Class Profile
}

Package Module {
Class Module
}


Package Course {
Class Course
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager *-- ProfileManager
ModelManager *-- ModuleManager
ModelManager *-- CourseManager
ProfileManager *-- ProfileList
ModuleManager *-- ModuleList
CourseManager *-- CourseList
ProfileList *-- "1"Profile
ModuleList *-- Module
CourseList *-- Course
ModelManager *-left- UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

@enduml

