 @startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Package Storage <<Rectangle>> {

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ProfileListStorage <<Interface>>
Interface ModuleListStorage <<Interface>>
Interface CourseListStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonProfileListStorage
Class JsonSerializableProfileList
Class JsonProfile
Class JsonSemesterRecord
Class JsonPersonalModule
Class JsonDeadline

Class JsonModuleListStorage
Class JsonSerializableModuleList
Class JsonModule
Class JsonSemesterData
Class JsonPrereqTreeNode

Class JsonCourseListStorage
Class JsonSerializableCourseList
Class JsonCourse
Class JsonCourseRequirement
Class JsonCourseFocusArea

}

StorageManager .right.|> Storage
StorageManager o-left- UserPrefsStorage
StorageManager o-- ProfileListStorage
StorageManager o-- ModuleListStorage
StorageManager o-- CourseListStorage

JsonUserPrefsStorage .right.|> UserPrefsStorage
JsonProfileListStorage .up.|> ProfileListStorage
JsonProfileListStorage .down.> JsonSerializableProfileList
JsonSerializableProfileList .down.> JsonProfile
JsonProfile *-right- JsonSemesterRecord
JsonSemesterRecord *-down- JsonPersonalModule
JsonPersonalModule *-down- JsonDeadline
JsonPersonalModule -left-|> JsonModule

JsonModuleListStorage .up.|> ModuleListStorage
JsonModuleListStorage .down.> JsonSerializableModuleList
JsonSerializableModuleList .down.> JsonModule
JsonModule *-down- JsonSemesterData
JsonModule *-down- JsonPrereqTreeNode

JsonCourseListStorage .up.|> CourseListStorage
JsonCourseListStorage .down.> JsonSerializableCourseList
JsonSerializableCourseList .down.> JsonCourse
JsonCourse *-down- JsonCourseRequirement
JsonCourse *-down- JsonCourseFocusArea
@enduml
